### ISSUE TITLE
control 360° sg90 servo

### ISSUE THREAD

**Issue by kyle99978** [Skipper7718/LiDAR#1]
Hi, I would like to know the code how to control 360° sg90 servo with Python.
Can you help me?
I would appreciate it if I could get your help!

**Comment by Skipper7718** [comment]
Are these 360° controlled servos or continuous spinning servos? If they are the latter, then You can adjust the mapping to the range, I assume. If they angle controlled and are the same duty cycles but with different angles, you can replace `servo.c - line 20` with:
`int duty_u16 = map(angle, 0, 360, DUTY_MIN, DUTY_MAX);`
At least I assume that may be a solution :thinking: I cannot test it as I dont have 360° servos.
If they are continuous without angle control, then the duty cycles represent speed.

Source file are in:
[servo.h](https://github.com/voidlight7718/LiDAR/blob/master/firmware/include/servo.h)
[servo.c](https://github.com/voidlight7718/LiDAR/blob/master/firmware/src/servo.c)

**Comment by kyle99978** [comment]
Thank you ！ That means to control the steering gear for continuous rotation. 
I'm sorry that I didn't make it clear that I wanted a Python code

**Comment by Skipper7718** [comment]
Okay, so you control speed, not angle... Okay :+1: 
```python
from machine import Pin, PWM

def speed(value, leftMin=0, leftMax=360, rightMin=2400, rightMax=9000):
    leftSpan = leftMax - leftMin
    rightSpan = rightMax - rightMin
    valueScaled = float(value - leftMin) / float(leftSpan)
    return round(rightMin + (valueScaled * rightSpan))


servo = PWM(Pin(0))
servo.freq(50)
servo.duty_u16(speed(90))
```

Maybe this does something :monocle_face:

**Comment by kyle99978** [comment]
import time
import RPi.GPIO as GPIO

GPIO.setmode(GPIO.BOARD)
GPIO.setup(11, GPIO.OUT)
pwm = GPIO.PWM(11, 50)  
pwm.start(0)
pwm.ChangeDutyCycle(1.45) #  1.45 means that control spped?
time.sleep(3)
pwm.stop()
Do you think this code is correct

**Comment by Skipper7718** [comment]
Ah okay I see. What you are looking for is neither A Raspberry Pi Pico Code nor Related to this project. If you want you can send me an Email under voidlight8166@gmail.com and we can continue there.

I will now close this issue since it has nothing to do with this project :smiley:
